package br.com.triadworks.leilaoweb.model.lists;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 30 17:39:25 GFT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LocaisDeEntregaViewListImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LocaisDeEntregaViewListImpl() {
    }
}

