package br.com.triadworks.leilaoweb.model.lists;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 30 16:21:19 GFT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StatusDaPromocaoViewListImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StatusDaPromocaoViewListImpl() {
    }
}

