package br.com.triadworks.leilaoweb.model;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 31 18:28:26 GFT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromocaoImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        DataEncerramento,
        LocalEntrega,
        Nome,
        ReceberEmDinheiro,
        Status,
        ValorMaximoLance,
        Lances;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int DATAENCERRAMENTO = AttributesEnum.DataEncerramento.index();
    public static final int LOCALENTREGA = AttributesEnum.LocalEntrega.index();
    public static final int NOME = AttributesEnum.Nome.index();
    public static final int RECEBEREMDINHEIRO = AttributesEnum.ReceberEmDinheiro.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int VALORMAXIMOLANCE = AttributesEnum.ValorMaximoLance.index();
    public static final int LANCES = AttributesEnum.Lances.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PromocaoImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public Long getId() {
        return (Long) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Long value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for DataEncerramento, using the alias name DataEncerramento.
     * @return the value of DataEncerramento
     */
    public Timestamp getDataEncerramento() {
        return (Timestamp) getAttributeInternal(DATAENCERRAMENTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DataEncerramento.
     * @param value value to set the DataEncerramento
     */
    public void setDataEncerramento(Timestamp value) {
        setAttributeInternal(DATAENCERRAMENTO, value);
    }

    /**
     * Gets the attribute value for LocalEntrega, using the alias name LocalEntrega.
     * @return the value of LocalEntrega
     */
    public String getLocalEntrega() {
        return (String) getAttributeInternal(LOCALENTREGA);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocalEntrega.
     * @param value value to set the LocalEntrega
     */
    public void setLocalEntrega(String value) {
        setAttributeInternal(LOCALENTREGA, value);
    }

    /**
     * Gets the attribute value for Nome, using the alias name Nome.
     * @return the value of Nome
     */
    public String getNome() {
        return (String) getAttributeInternal(NOME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nome.
     * @param value value to set the Nome
     */
    public void setNome(String value) {
        setAttributeInternal(NOME, value);
    }

    /**
     * Gets the attribute value for ReceberEmDinheiro, using the alias name ReceberEmDinheiro.
     * @return the value of ReceberEmDinheiro
     */
    public Integer getReceberEmDinheiro() {
        return (Integer) getAttributeInternal(RECEBEREMDINHEIRO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceberEmDinheiro.
     * @param value value to set the ReceberEmDinheiro
     */
    public void setReceberEmDinheiro(Integer value) {
        setAttributeInternal(RECEBEREMDINHEIRO, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for ValorMaximoLance, using the alias name ValorMaximoLance.
     * @return the value of ValorMaximoLance
     */
    public BigDecimal getValorMaximoLance() {
        return (BigDecimal) getAttributeInternal(VALORMAXIMOLANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValorMaximoLance.
     * @param value value to set the ValorMaximoLance
     */
    public void setValorMaximoLance(BigDecimal value) {
        setAttributeInternal(VALORMAXIMOLANCE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getLances() {
        return (RowIterator) getAttributeInternal(LANCES);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("br.com.triadworks.leilaoweb.model.Promocao");
    }

     /**
      * Metodo invocado pelo ADF sempre que se cria uma instancia nova da entidade
      */
     protected void create(AttributeList attributeList) {
         super.create(attributeList);
         // preenche campo com valor da sequence
         SequenceImpl sequence = new SequenceImpl("SEQ_PROMOCAO", getDBTransaction());
         setId(sequence.getSequenceNumber().longValue());
     }
}

