CREATE TABLE TB_FUNCIONARIO
  (
    ID    NUMBER(10,0) NOT NULL,
    CPF   VARCHAR2(11 CHAR) NOT NULL,
    EMAIL VARCHAR2(60 CHAR),
    NOME  VARCHAR2(60 CHAR) NOT NULL,
    PRIMARY KEY (ID)
  );
  
CREATE TABLE TB_LANCE
  (
    ID           NUMBER(10,0) NOT NULL,
    CUPOM_NUMERO VARCHAR2(10 CHAR),
    DATA_CRIACAO TIMESTAMP,
    VALOR DOUBLE PRECISION NOT NULL,
    CLIENTE_ID  NUMBER(10,0) NOT NULL,
    PROMOCAO_ID NUMBER(10,0),
    PRIMARY KEY (ID)
  );
  
CREATE TABLE TB_PROMOCAO
  (
    ID                  NUMBER(10,0) NOT NULL,
    DATA_ENCERRAMENTO   DATE NOT NULL,
    LOCAL_ENTREGA       VARCHAR2(60 CHAR),
    NOME                VARCHAR2(80 CHAR) NOT NULL,
    RECEBER_EM_DINHEIRO NUMBER(1,0),
    STATUS              VARCHAR2(40 CHAR) NOT NULL,
    VALOR_MAXIMO_LANCE DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (ID)
  );
  
CREATE TABLE TB_USUARIO
  (
    ID    NUMBER(10,0) NOT NULL,
    LOGIN VARCHAR2(20 CHAR) NOT NULL,
    NOME  VARCHAR2(60 CHAR) NOT NULL,
    SENHA VARCHAR2(60 CHAR) NOT NULL,
    PRIMARY KEY (ID)
  );
  

ALTER TABLE TB_FUNCIONARIO ADD CONSTRAINT UK_FUNCIONARIO_CPF UNIQUE (CPF);
ALTER TABLE TB_USUARIO ADD CONSTRAINT UK_USUARIO_LOGIN UNIQUE (LOGIN);

ALTER TABLE TB_LANCE ADD CONSTRAINT FK_LANCE_CLIENTE_ID FOREIGN KEY (CLIENTE_ID) REFERENCES TB_FUNCIONARIO;
ALTER TABLE TB_LANCE ADD CONSTRAINT FK_LANCE_PROMOCAO_ID FOREIGN KEY (PROMOCAO_ID) REFERENCES TB_PROMOCAO;

CREATE sequence SEQ_FUNCIONARIO;
CREATE sequence SEQ_LANCE;
CREATE sequence SEQ_PROMOCAO;
CREATE sequence SEQ_USUARIO;