--
-- Cria Schema (user)
--
drop user leilao_web cascade;
create user leilao_web identified by "123";
grant connect to leilao_web;
grant create session to leilao_web;
grant dba to leilao_web;

--
-- Cria objetos do schema
--
CREATE TABLE leilao_web.TB_FUNCIONARIO
  (
    ID    NUMBER(10,0) NOT NULL,
    CPF   VARCHAR2(11 CHAR) NOT NULL,
    EMAIL VARCHAR2(60 CHAR),
    NOME  VARCHAR2(60 CHAR) NOT NULL,
    PRIMARY KEY (ID)
  );
  
CREATE TABLE leilao_web.TB_LANCE
  (
    ID              NUMBER(10,0) NOT NULL,
    CUPOM_NUMERO    VARCHAR2(10 CHAR),
    DATA_CRIACAO    TIMESTAMP,
    VALOR           NUMBER(14,2) NOT NULL,
    FUNCIONARIO_ID  NUMBER(10,0) NOT NULL,
    PROMOCAO_ID     NUMBER(10,0),
    PRIMARY KEY (ID)
  );
  
CREATE TABLE leilao_web.TB_PROMOCAO
  (
    ID                  NUMBER(10,0) NOT NULL,
    DATA_ENCERRAMENTO   DATE NOT NULL,
    LOCAL_ENTREGA       VARCHAR2(60 CHAR),
    NOME                VARCHAR2(80 CHAR) NOT NULL,
    RECEBER_EM_DINHEIRO NUMBER(1,0),
    STATUS              VARCHAR2(40 CHAR) NOT NULL,
    VALOR_MAXIMO_LANCE  NUMBER(14,2) NOT NULL,
    PRIMARY KEY (ID)
  );
  
CREATE TABLE leilao_web.TB_USUARIO
  (
    ID    NUMBER(10,0) NOT NULL,
    LOGIN VARCHAR2(20 CHAR) NOT NULL,
    NOME  VARCHAR2(60 CHAR) NOT NULL,
    SENHA VARCHAR2(60 CHAR) NOT NULL,
    PRIMARY KEY (ID)
  );
  

ALTER TABLE leilao_web.TB_FUNCIONARIO ADD CONSTRAINT UK_FUNCIONARIO_CPF UNIQUE (CPF);
ALTER TABLE leilao_web.TB_USUARIO ADD CONSTRAINT UK_USUARIO_LOGIN UNIQUE (LOGIN);

ALTER TABLE leilao_web.TB_LANCE ADD CONSTRAINT FK_LANCE_FUNCIONARIO_ID FOREIGN KEY (FUNCIONARIO_ID) REFERENCES leilao_web.TB_FUNCIONARIO;
ALTER TABLE leilao_web.TB_LANCE ADD CONSTRAINT FK_LANCE_PROMOCAO_ID FOREIGN KEY (PROMOCAO_ID) REFERENCES leilao_web.TB_PROMOCAO;

CREATE sequence leilao_web.SEQ_FUNCIONARIO;
CREATE sequence leilao_web.SEQ_LANCE;
CREATE sequence leilao_web.SEQ_PROMOCAO;
CREATE sequence leilao_web.SEQ_USUARIO;

--
-- Popula tabelas
--
INSERT INTO leilao_web.TB_USUARIO(ID, LOGIN, NOME, SENHA)
  VALUES(leilao_web.SEQ_USUARIO.nextval, 'admin', 'Administrador', '123@');